{"trial_id": "02", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "output_units", "default": null, "conditions": [], "min_value": 1, "max_value": 20, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "layers", "default": null, "conditions": [], "min_value": 2, "max_value": 6, "step": 1, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "learning_rate", "default": 0.0001, "conditions": [], "min_value": 0.0001, "max_value": 0.1, "step": null, "sampling": "log"}}, {"class_name": "Int", "config": {"name": "units_0", "default": null, "conditions": [], "min_value": 16, "max_value": 256, "step": 16, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 16, "max_value": 256, "step": 16, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers", "default": 5, "conditions": [], "min_value": 2, "max_value": 50, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units", "default": null, "conditions": [], "min_value": 8, "max_value": 64, "step": 8, "sampling": "linear"}}, {"class_name": "Boolean", "config": {"name": "dropout", "default": false, "conditions": []}}], "values": {"output_units": 6, "layers": 2, "learning_rate": 0.004774206037940447, "units_0": 128, "units_1": 208, "num_layers": 5, "units": 8, "dropout": false}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\hanna\\Documents\\University\\Year 4\\DAML\\env\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\hanna\\Documents\\University\\Year 4\\DAML\\env\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 238, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\hanna\\Documents\\University\\Year 4\\DAML\\env\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\hanna\\Documents\\University\\Year 4\\DAML\\env\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\hanna\\Documents\\University\\Year 4\\DAML\\env\\Lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\hanna\\Documents\\University\\Year 4\\DAML\\env\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"c:\\Users\\hanna\\Documents\\University\\Year 4\\DAML\\env\\Lib\\site-packages\\keras\\src\\engine\\data_adapter.py\", line 1960, in _check_data_cardinality\n    raise ValueError(msg)\nValueError: Data cardinality is ambiguous:\n  x sizes: 70018\n  y sizes: 30008\nMake sure all arrays contain the same number of samples.\n"}